

networks:
  def:

services:
  bot:
    build: 
      context: './bot'
      dockerfile: Dockerfile  
    restart: unless-stopped  
    environment:
      - TOKEN
      - NGINX_HOST
    ports:
      - "7000:7000"
    networks:
      - def  

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      - NGINX_HOST
    volumes:
      - './nginx/first_start/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './certbot/www:/var/www/certbot:rw'  # Изменили на rw
    networks:
      - def

  certbot:
    image: certbot/certbot:v4.0.0
    volumes:
      - './certbot/www:/var/www/certbot:rw'
      - './certbot/conf:/etc/letsencrypt:rw'
    command: sh -c "sleep 10 && certbot certonly --webroot --webroot-path /var/www/certbot --email romaa251205@gmail.com -d ${NGINX_HOST} --agree-tos --non-interactive --dry-run"
    depends_on:
      - nginx
    networks:
      - def