networks:
  def:

services:
  bot:
    build: 
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - TOKEN=$${TOKEN}
      - NGINX_HOST=$${NGINX_HOST}
    ports:
      - "7000:7000"
    networks:
      - def  

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=$${NGINX_HOST}
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './certbot/www:/var/www/certbot'
      - './certbot/conf:/etc/letsencrypt'
    depends_on:
      - bot
    networks:
      - def

  certbot:
    image: certbot/certbot:v4.0.0
    volumes:
      - './certbot/www:/var/www/certbot'
      - './certbot/conf:/etc/letsencrypt'
    command: ["sh", "-c", "sleep 15 && certbot certonly --webroot --webroot-path /var/www/certbot --email romaa251205@gmail.com -d $${NGINX_HOST} --agree-tos --non-interactive"]
    depends_on:
      - nginx
    networks:
      - def