networks:
  def:

services:
  bot:
    build: 
      context: './bot'
      dockerfile: Dockerfile  
    restart: unless-stopped  
    environment:
      - TOKEN
      - NGINX_HOST
    ports:
      - "7000:7000"
    depends_on:
      - nginx
    networks:
      - def  

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      - NGINX_HOST
    volumes:
      - './nginx/first_start/:/etc/nginx/templates/:ro'
      # - './nginx/templates/:/etc/nginx/templates/:ro'
      - './certbot/www:/var/www/certbot/:ro'
      - './certbot/conf/:/etc/nginx/ssl/:ro'
    depends_on:
      - certbot
    networks:
      - def   

  certbot:
    image: certbot/certbot:v4.0.0
    volumes:
      - './certbot/www:/var/www/certbot:rw'
      - './certbot/conf:/etc/letsencrypt:rw'
    networks:
      - def 