services:
  bot:
    build: 
      context: ./bot
      dockerfile: Dockerfile  
    restart: unless-stopped  
    environment:
      - TOKEN=${TOKEN}
      - NGINX_HOST=${NGINX_HOST}
      - ADMIN_ID=${ADMIN_ID}
      - ADMIN_ID2=${ADMIN_ID2}
      - PHONE=${PHONE} 
    ports:
      - "3001:3001"
    depends_on:
      - nginx  

  nginx:
    image: nginx:1.28.0-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
    depends_on:
      - certbot  

  certbot:
    image: certbot/certbot:v4.0.0
    command: sh -c "sleep 10 && certbot certonly --standalone -d ${NGINX_HOST} --email your-email@example.com --agree-tos --non-interactive --keep-until-expiring"
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw